PYTHON=python3

run_tests: run_accelerator_test run_main_buffer_test run_processing_element_test
	
run_accelerator_test:
	$(PYTHON) test_accelerator.py

run_main_buffer_test:
	$(PYTHON) test_main_buffer.py

run_processing_element_test:
	$(PYTHON) test_processing_element.py